version: "3.9"

services:
  database:
    image: postgres
    container_name: allTodos
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRESS_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
